### ISSUE TITLE
Stuck on Initializing ActionScript & MXML language server...

### ISSUE THREAD

**Issue by benjaminbarbe** [BowlerHatLLC/vscode-as3mxml#431]
Hello,

I would like to use Code Intelligence but I'm stuck with: 
![image](https://user-images.githubusercontent.com/630365/70146529-a8291880-16a2-11ea-9d4d-13f094690549.png)

I didn't specify ```target-player``` in asconfig because it's above 10.1 in the sdk.
Nothings appears wrong too:
![image](https://user-images.githubusercontent.com/630365/70146615-da3a7a80-16a2-11ea-83a5-b6a6a8523a78.png)

Compilation works fine.

Here is the asconfig.json:

```json
{
	"config": "flex",
	"compilerOptions": {
		"output": "bin-debug/index.swf",
		"source-path": [
			"src",
			"bein-as3-core/src"
		],
		"library-path": [
			"libs",
			"${flexlib}/libs/mobile/mobilecomponents.swc",
			"bein-as3-core/libs"
		]
	},
	"files": [
		"src/index.mxml"
	],
	"copySourcePathAssets": true,
	"htmlTemplate": "html-template",
	"additionalOptions": "-incremental=true -locale=en_US,fr_FR -source-path=locale/{locale} -swf-version=18 -define+=CONFIG::debugging,true -define+=CONFIG::release,false -define+=NAMES::version,\"[developer]\" -define+=NAMES::domain,\"domain.dev\" -define+=NAMES::urlWs,\"https://domain.dev:5000/\" -define+=NAMES::urlWsData,\"https://domain.dev:5000/\" -define+=NAMES::authoringAssetsUrl,\"https://domain.dev:5000/1.1.1/\""
}
```

Do you have any ideas to resolve this? or maybe debug?

Thanks

**Comment by joshtynjala** [comment]
Try removing `-incremental=true` from the `additionalOptions`.

**Comment by benjaminbarbe** [comment]
Unfortunately same problem.

**Comment by joshtynjala** [comment]
I created an empty project using your asconfig.json file, but unfortunately, I could not reproduce the issue. Code intelligence was working correctly for me. It must be some other aspect of your project that is causing the issue. Unfortunately, that's probably going to be hard to debug.

I'd like you to check to see if any errors are reported by the as3mxml language server.

1. Go to the **View** menu and choose **Output**
1. In the Output view, open the drop-down and choose **ActionScript & MXML Language Server**
1. Copy/paste any output you see here in a comment

It's possible that the language server won't be in the drop-down at all, so don't worry if you can't find it. Just let me know if that you don't see it.

Thanks!

**Comment by joshtynjala** [comment]
Also, which SDK (including version) are you using?

**Comment by joshtynjala** [comment]
I had a few extra minutes today, so I tried playing around with some more things. Your asconfig.json file should not be able to compile successfully. I get the following error when I try:

> C:\Users\josht\Desktop\TestProject\src\index.mxml(-1):  Error: The initializer for a configuration value must be a compile time constant.

It's weird, but when you define conditional compilation constants that are strings, they need to be wrapped in two sets of quotes. That's because one set of quotes is parsed as an expression. "1 + 2" is parsed as the number `3`, so using two sets of quotes like "'1 + 2'" would be how you'd get the string "1 + 2".

Anyway, a define like this:

```
-define+=NAMES::domain,\"domain.dev\"
```

Should actually be specified like this (notice the single quote ' inside each double quote:

```
-define+=NAMES::domain,\"'domain.dev'\"
```

Now, I still haven't been able to reproduce your original issue, so this may not be related at all. However, I thought that I'd point it out.

**Comment by joshtynjala** [comment]
By the way, if you make any changes to asconfig.json as a potential fix when _Initializing ActionScript & MXML..._ gets stuck, you should always reload VSCode to test whether it worked or not. Just in case you weren't doing that already.

**Comment by benjaminbarbe** [comment]
Thanks for all your time.

Unfortunately, I haven't any **ActionScript & MXML Language Server** logs.
[SDK version is 4.13.0 - download my version here](https://send.firefox.com/download/ef4f92a118a8401b/#-SoCXzbAAPDMfEMDLq38_A)

For the conditional compilation constants, it's true with my old flash builder configuration. But for now with the single quote, it try to call the domain 'domain.dev' and result in a http error.

Without, I can confirm the build step finish successfully.

```
> Executing task: /usr/bin/java -jar $HOME/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.24.1/bin/asconfigc.jar --sdk $PROJECT_ROOT/sdks/4.13.0 --debug=true --project $PROJECT_ROOT/asconfig.json <

Loading configuration file $PROJECT_ROOT/sdks/4.13.0/frameworks/flex-config.xml
$PROJECT_ROOT/bin-debug/index.swf (5617922 bytes)
```

And yes I have tried the : Restart ActionScript Server from the menu and close/reopen vscode. It didn't help!

Thanks again.

**Comment by joshtynjala** [comment]
Interestingly, when I tried your 4.13.0 SDK, I still had the same error when I omitted the extra quotes. It's strange that we're seeing different behavior.

I can see that your on macOS, and I'm on Windows primarily. I'll do some tests on macOS too, to see if I can reproduce there.

If that doesn't work, the only option left is probably for you to share your entire project with me. I'm sure that we can find a way to do that privately, if necessary.

**Comment by joshtynjala** [comment]
Unfortunately, I could not reproduce the initializing freeze on my macOS computer either. It seems to be some other aspect of your project that has the issue.

I found that the -define compiler option does behave as you describe on macOS. I'm not sure why there's a difference between the two platforms. That's concerning, but not really related to your main issue, so sorry for adding noise to the conversation.

At this point, there's not much else that I can do to help, unless I can get access to your full project. Would it be possible to share it with me? You can email me using my Github username at bowlerhat.dev, if necessary.

**Comment by jnpatrick99** [comment]
By the way I have the same problem as well! 

I cannot use this plugin at all recently on any of my projects. 
Some projects just get stuck on "Initializing ActionScript & MXML language server" and some freeze during code intelligence phase (so I have to kill java process).

This all happens on macOS Mojave 10.14.6 by the way.

**Comment by joshtynjala** [comment]
Probably the best way to find the cause is start completely removing .as and .mxml classes from your project until it can initialize properly. If someone can narrow it down to the bare minimum required to reproduce the issue, I should be able to fix it. The problem is that all of my projects work fine, so I cannot reproduce the issue.

Alternatively, if someone can send me a full project, that would probably allow me to do it all. However, I understand that might not be possible for everyone.

**Comment by karisN** [comment]
I have the same issue. What I found out if my project is large, the language server will hang. Small projects are fine. Perhaps it's a JVM memory issue?

**Comment by joshtynjala** [comment]
@karisN I just released vscode-as3mxml v1.2.0. Please try the new `as3mxml.languageServer.jvmargs` setting to see if it helps with the issue. I believe that you can increase the amount of memory Java uses with the -Xmx option, like this:

```json
"as3mxml.languageServer.jvmargs": "-Xmx1024m"
```

**Comment by benjaminbarbe** [comment]
Unfortunately, that doesn't fix the problem on my end.
Thanks anyway, Josh.

**Comment by karisN** [comment]
Unfortunately it's still stuck even after pushing Mxm to 4096 for a larger project. Thanks though!
